name: KEYS

on:
  workflow_dispatch: {}
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  check-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check keys file format
        shell: bash
        run: ./.github/workflows/check_keys.sh
